Controllers/AvailabilityController.cs
/**
 * Author:    Alejandro Serrano
 * Partner:   None
 * Date:      11/21/2021
 * Course:    CS 4540, University of Utah, School of Computing
 * Copyright: CS 4540 and Alejandro Serrano - This work may not be copied for use in Academic Coursework.
 *
 * I, Alejandro Serrano, certify that I wrote this code from scratch and did
 * not copy it in part or whole from another source.  Any references used
 * in the completion of the assignment are cited in my README file and in
 * the appropriate method header.
 *
 * File Contents
 *
 * Controller that handles the Availability view. Saves the new schedule after receiving a post from
 * JavaScript code. 
 */


using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PS4_TAApplication.Data;
using PS4_TAApplication.Models;

namespace PS4_TAApplication.Controllers
{
    public class AvailabilityController : Controller
    {
        private readonly Avail_DB _context;
        public AvailabilityController(Avail_DB context)
        {
            _context = context;
        }

        public async Task<IActionResult> Avail()
        {
            return View(await _context.Availabilities.ToListAsync());
        }
        /// <summary>
        /// Saves the new schedule entered by the user in the application. 
        /// </summary>
        /// <param name="sch">schedule to be saved</param>
        /// <param name="id">id of the user</param>
        /// <returns></returns>
        public async Task<IActionResult> SaveSchedule(string sch, int? id)
        {
            if (sch == null){
                return Ok(BadRequest("Schedule is NULL"));
            }
            if (id == null){
                return Ok(BadRequest("Id is null"));
            }
            var userAvailability = await _context.Availabilities.FindAsync(id);
            if (userAvailability == null){
                return Ok(BadRequest("Availability is null"));
            }

            userAvailability.Date = sch;
            _context.SaveChanges();
            return View(Avail());
        }
    }

    
}

Controllers/ChartController.cs
/**
 * Author:    Alejandro Serrano
 * Partner:   None
 * Date:      12/9/2021
 * Course:    CS 4540, University of Utah, School of Computing
 * Copyright: CS 4540 and Alejandro Serrano - This work may not be copied for use in Academic Coursework.
 *
 * I, Alejandro Serrano, certify that I wrote this code from scratch and did
 * not copy it in part or whole from another source.  Any references used
 * in the completion of the assignment are cited in my README file and in
 * the appropriate method header.
 *
 * File Contents
 *
 * Handles the database information by returning a view with the list of courses and enrollments.  
 *  
 */

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PS4_TAApplication.Data;
using PS4_TAApplication.Models;
using System.Collections;

namespace PS4_TAApplication.Controllers
{
    public class ChartController : Controller
    {

        private readonly CourseEnrollContext _context;

        public ChartController(CourseEnrollContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Considering this similar to what the enrollmentTrends method is described to do. 
        /// It returns the model of the database. 
        /// </summary>
        /// <returns></returns>
        public IActionResult Charts()
        {
            return View(_context.CourseEnrollments.ToList());
        }

        public IActionResult PieChart()
        {
            return View(_context.CourseEnrollments.ToList());
        }
        /// <summary>
        /// Returns a list of enrollments based on the start and end date
        /// </summary>
        /// <param name="course">query course</param>
        /// <param name="start">start date</param>
        /// <param name="end"> end date </param>
        /// <returns></returns>
        public ArrayList GetEnrollment(string course, int? start, int? end)
        {
            var courses = _context.CourseEnrollments.ToList();
           
            ArrayList q = new ArrayList();
            List<Enrollment> enrollmentOfOneCourse = new List<Enrollment>();
    
            CourseEnrollment c = null;
            foreach(var val in courses)
            {
                if (val.CourseName.Equals(course))
                {
                    c = val;
                    break;
                }
            }

            var enroll = _context.Enrollments.ToList();

            enroll.Sort((x,y) => x.CourseID.CompareTo(y.CourseID));
            
            foreach(var e in enroll)
            {
                if(c.ID == e.CourseID)
                {
                    enrollmentOfOneCourse.Add(e);
                }
            }

            enrollmentOfOneCourse.Sort((x, y) => x.EnrollmentData.CompareTo(y.EnrollmentData));

            foreach(Enrollment e in enrollmentOfOneCourse)
            {
                q.Add(e.EnrollmentQuantity);
            } 
            
            int sizeOfFinalArray = (int)(end - start);
            ArrayList f = new ArrayList();

            for(int i = (int)start; i <= (int)end; i ++ )
            {
                f.Add(q[i]);
            }

            return f;

        }

    }
}

Controllers/CoursesController.cs
/*
< !--
    Author:    Alejandro Serrano
    Partner:   None
    Date:      10 / 25 / 2021
    Course: CS 4540, University of Utah, School of Computing
    Copyright: CS 4540 and Alejandro Serrano - This work may not be copied for use in Academic Coursework.

    I, Alejandro Serrano, certify that I scaffolded this code from scratch and did not copy it in part or whole from
    another source.  Any references used in the completion of the assignment are cited in my README file.

    File Contents

    Controller for Couses model
  -->
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PS4_TAApplication.Data;
using PS4_TAApplication.Models;

namespace PS4_TAApplication.Controllers
{
    public class CoursesController : Controller
    {
        private readonly Course_DB _context;

        public CoursesController(Course_DB context)
        {
            _context = context;
        }

        [Authorize(Roles = "Administrator, Applicant, Professor")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize (Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("ID,SemestersOffered,YearsOffered,Title,Department,CourseNumber,Section,ProfUnid,ProfName,TimeDay,Location,CreditHours,Capacity,Note")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,SemestersOffered,YearsOffered,Title,Department,CourseNumber,Section,ProfUnid,ProfName,TimeDay,Location,CreditHours,Capacity,Note")] Course course)
        {
            if (id != course.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.ID == id);
        }

        /// <summary>
        /// Allows admin to add notes to courses. 
        /// </summary>
        /// <param name="note"> Note to add to course model</param>
        /// <param name="course_id">id of the course for updating</param>
        /// <returns>Returns view if course is retrieved succesfully, otherwise a bad request</returns>
        public async Task<IActionResult> SubmitNote(string note, int? course_id)
        {
            if(note == null)
            {
                return Ok(BadRequest("Note is null"));
            }
            
            if(course_id == null)
            {
                return Ok(BadRequest("Id is null"));
            }
            var course = await _context.Courses.FindAsync(course_id);
            

            if(course == null)
            {
                return Ok(BadRequest("Course is null"));
            }

            course.Note = note;
            _context.SaveChanges();
            

         

            return View(Index());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PS6_Courses_Google</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)
    <link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/pixi.js/6.2.0/browser/pixi.js'></script>
</head>
@using Microsoft.AspNetCore.Identity
@using PS4_TAApplication.Areas.Identity.Data
@using System.Security.Claims;
@using PS4_TAApplication.Models
@inject SignInManager<TAUser> SignInManager
@inject UserManager<TAUser> UserManager


<body style="background-color: antiquewhite">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container d-flex flex-column flex-md-row justify-content-between"  >
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PS6_Courses_Google</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chart" asp-action="Charts">Line Chart </a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chart" asp-action="PieChart">Pie Chart </a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Availability" asp-action="Avail">Avail </a>
                        </li>
                        <li>
                            <div class="dropdown">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                    TA App!
                                </button>
                                <div class="dropdown-menu">
                                    <p>Alejandro Serrano</p>
                                    <a class="dropdown-item" href=/Courses/Index>Course List</a>
                                    <a asp-controller="Courses" asp-action="Details" asp-route-id=1>
                                        Details Course 1
                                    </a>
                                    <a asp-controller="Courses" asp-action="Edit" asp-route-id=1>
                                        Edit Course 1
                                    </a>
                                    <a asp-controller="Courses" asp-action="Create">
                                        Create a Course
                                    </a>

                                    <a class="dropdown-item" href=/Applications/Edit/1>Edit Page</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PS4_TAApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>